### ISSUE TITLE
URLs only valid with 'http(s)://' prefix

### ISSUE THREAD

**Issue by murjax** [nikkypx/ping_thing#3]
Currently this gem only allows urls with the full protocol and domain. I was wondering if we could 
allow urls without the http protocol prefix. I think it would be more user intuitive to allow a url such as 'hashrocket.com' instead of 'https://hashrocket.com', as is required now in order to parse. When I am entering a url into my browser, typically I enter it in the former fashion, so I think it would be a good idea to carry that functionality over into this gem for easier typing.

**Comment by nikkypx** [comment]
Hey Ryan, we could do this. What do you @vnegrisolo

**Comment by murjax** [comment]
Definitely. I'll write up a solution and then open a pull request for it when I'm done. Thanks.
